#ifndef PHONONAUDIO_GLOBAL_H
#define PHONONAUDIO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHONONAUDIO_LIBRARY)
#  define PHONONAUDIOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHONONAUDIOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHONONAUDIO_GLOBAL_H
